### ISSUE TITLE
version 0.2.2 have syntax issues run with python2.7 and python 3.5 getting SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nirIndegy** [fruch/pytest-elk-reporter#24]
python 3
```
root@15cb601c3ec8:/# pip3 install pytest-elk-reporter
Collecting pytest-elk-reporter
  Using cached 
https://files.pythonhosted.org/packages/f6/1a/27a859e42329bb0966220ae908a1de2aa75d98ec567736e77c5352166254/pytest_elk_reporter-0.2.2-py2.py3-none-any.whl
Requirement already satisfied: pytest>=3.5.0 in /usr/local/lib/python3.5/dist-packages (from pytest-elk-reporter)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pytest-elk-reporter)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from pytest-elk-reporter)
Requirement already satisfied: packaging in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: more-itertools>=4.0.0; python_version > "2.7" in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.5/dist-packages (from pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->pytest-elk-reporter)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->pytest-elk-reporter)
Requirement already satisfied: idna<2.6,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->pytest-elk-reporter)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->pytest-elk-reporter)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.5/dist-packages (from packaging->pytest>=3.5.0->pytest-elk-reporter)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.5/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=3.5.0->pytest-elk-reporter)
Installing collected packages: pytest-elk-reporter
Successfully installed pytest-elk-reporter-0.2.2

root@15cb601c3ec8:/# python3 -m pytest  -k my_test_case --es-address 10.100.30.20:9200
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytest.py", line 102, in <module>
    raise SystemExit(pytest.main())
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 65, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 214, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 789, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 997, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/config/__init__.py", line 943, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/pytest_elk_reporter.py", line 384
    print(f"Error while deleting file {filename}")
                                                ^
SyntaxError: invalid syntax
```

in 2.7
```
root@15cb601c3ec8:/# pytest  -k test_create_new_policies_for_all_events_by_telegy --es-address 10.100.30.20:9200
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 65, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 214, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 789, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 997, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 943, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pytest_elk_reporter.py", line 262
    **self.session_data,
                       ^

SyntaxError: invalid syntax
```

**Comment by fruch** [comment]
hmm, seems like we are using f-strings.
